# Site settings
title: Maria Messineo
email: messineo.archeo@gmail.com
description: Personal Portfolio
baseurl: "/spectral-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/Tearwork
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: https://www.linkedin.com/in/maria-messineo/
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
